variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CHANGELOG_FILE: "changelog.txt"
  XCARCHIVE_NAME: "App.xcarchive"
  XCZIP_NAME: "App.zip"
  IPA_NAME: "App.ipa"

.set_build_number: &set_build_number
  - export BUILD_NUMBER=$(echo $CI_COMMIT_TAG | rev | cut -d '/' -f1 | rev)

.collect_changelog: &collect_changelog
  - fastlane run changelog_from_git_commits tag_match_pattern:build/* | grep -E '^([a-zA-Z]*-.*)' | sed 's/^\([a-zA-Z]*-[0-9]*\).*$/\1/' | sort | uniq |  tr '\n' ',' | sed 's/\(.*\),/\1/' > ${CHANGELOG_FILE} || true

.build_ios_mpp_moko: &build_ios_mpp_moko
  - cd ./ios-app
  - pod install --repo-update
  - cd ..
  - ./gradlew syncMultiPlatformLibraryReleaseFrameworkIosArm64
  - cd ./ios-app

## Following environments should be provided before job 'script' section called
## 1. match group (team):
# MATCH_PASSWORD      //gitlab env
# FASTLANE_USER       //gitlab env
# FASTLANE_TEAM_ID
# FASTLANE_PASSWORD   //gitlab env
# MATCH_GIT_BRANCH
# MATCH_GIT_URL
# FASTLANE_DONT_STORE_PASSWORD
## 2. project group:
# FIREBASE_TOKEN
# BUILD_APP_IDENTIFIER
# BUILD_SCHEME
# FIREBASE_APP_ID
## additional commands should be called in 'before_script' section
.build_ios_mpp: &build_ios_mpp
  stage: build
  script:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US.UTF-8
    - export LC_ALL=en_US.UTF-8
    - *set_build_number
    - *collect_changelog
    - *build_ios_mpp_moko
    - fastlane build
  artifacts:
    paths:
      - ./ios-app/${XCZIP_NAME}
      - ${CHANGELOG_FILE}
    expire_in: 2 days
  except:
    - branches
  tags:
    - gradle
    - fastlane
    - osx
    - xcode

## Following environments should be provided before job 'script' section called
## 1. match group (team):
# MATCH_PASSWORD      //gitlab env
# FASTLANE_USER       //gitlab env
# FASTLANE_TEAM_ID
# FASTLANE_PASSWORD   //gitlab env
# MATCH_GIT_BRANCH
# MATCH_GIT_URL
# FASTLANE_DONT_STORE_PASSWORD
## 2. project group:
# FIREBASE_TOKEN
# BUILD_APP_IDENTIFIER
# BUILD_SCHEME
# FIREBASE_APP_ID
## additional commands should be called in 'before_script' section
.deploy_ios_mpp_firebase: &deploy_ios_mpp_firebase
  stage: deploy
  script:
    - mv ${CHANGELOG_FILE} ./ios-app/
    - cd ./ios-app
    - fastlane deploy_firebase
  artifacts:
    paths:
      - ./ios-app/${IPA_NAME}
      - ${CHANGELOG_FILE}
    expire_in: 2 days
  tags:
    - fastlane
    - xcode
    - osx

## Following environments should be provided before job 'script' section called
## 1. match group (team):
# MATCH_PASSWORD      //gitlab env
# FASTLANE_USER       //gitlab env
# FASTLANE_TEAM_ID
# FASTLANE_PASSWORD   //gitlab env
# MATCH_GIT_BRANCH
# MATCH_GIT_URL
# FASTLANE_DONT_STORE_PASSWORD
## 2. project group:
# FIREBASE_TOKEN
# BUILD_APP_IDENTIFIER
# BUILD_SCHEME
# FIREBASE_APP_ID
## additional commands should be called in 'before_script' section
.deploy_ios_firebase: &deploy_ios_firebase
  stage: deploy
  script:
    - fastlane deploy_firebase
  artifacts:
    paths:
      - ${IPA_NAME}
      - ${CHANGELOG_FILE}
    expire_in: 2 days
  tags:
    - fastlane
    - xcode
    - osx